---
- name: Create user with SSH key access
  hosts: all
  become: yes
  # vars_files:
  #  - accessvm.yaml
  vars:
    username: chernyavsky # username с которым будете подключаться
    user_password: "{{ 'qcdKqaM8' | password_hash('sha512') }}" # пароль
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 

  tasks:
    - name: Create user {{ username }} (Debian/Ubuntu)
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ username }}"
        groups: sudo
        append: yes
        state: present
      ignore_errors: yes
      when: ansible_os_family == "Debian"
      
    - name: Create user {{ username }} (RHEL-based systems)
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        shell: /bin/bash
        create_home: yes
        home: "/home/{{ username }}"
        groups: wheel
        append: yes
        state: present
      ignore_errors: yes
      when: ansible_os_family in ["RedHat", "RedOS", "CentOS", "RED"]

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add SSH public key
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_public_key }}"
        state: present
        manage_dir: yes

    - name: Set proper permissions for SSH directory
      file:
        path: "/home/{{ username }}/.ssh"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
        recurse: yes

    - name: Add user to sudoers with NOPASSWD
      lineinfile:
        path: "/etc/sudoers.d/{{ username }}"
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        state: present
        create: yes
        mode: '0440'
        validate: 'visudo -cf %s'
      tags: sudoers
    
    # - name: Ensure SSH service is running
    #   service:
    #     name: "{{ 'ssh' if ansible_os_family == 'Debian' else 'sshd' }}"
    #     state: started
    #     enabled: yes

    - name: Display test result
      debug:
        msg: "===== PLAYBOOK COMPLETE ====="
